### PR TITLE
Fixing template structure

### LINKED ISSUE #8: Change templates structure
Templates should be something like:

```
exports.templates = {
	basic: [
	'Werewolves',
	'Villagers',
	],

	novice: [
	'Werewolves',
	'Villagers',
	'Seer',
	'Mayor'
	],

	amateur: [
	'Werewolves',
	'Wolf cub',
	'Villagers',
	'Mayor',
	'Seer',
	'Witch',
	'Prince',
	'Tanner'
	],

	wolfpack: [
	'Werewolves',
	'Big Bad Wolf',
	'Wolf Cub',
	'Lone Wolf',
	'Fruit Brute',
	'Dream Wolf',
	'Villagers',
	'Seer',
	'Prince',
	'Mayor',
	'Martyr'
	],

	competent: [
	'Werewolves',
	'Wolf cub',
	'Sorcerer',
	'Cursed',
	'Minion',
	'Wild Child',
	'Villagers',
	'Mayor',
	'Seer',
	'Witch',
	'Prince',
	'Cult Leader',
	'Cupid',
	'Diseased',
	'Doppelgänger',
	'Lycan',
	'Spellcaster',
	'Tanner',
	'Mason',
	'Bodyguard',
	'Apprentice Seer',
	'Drunk'
	]
}
```

### PR DESCRIPTION
**Pull request by wistcc**
This closes #8

### CODE REVIEW

File: cards.js [hunk 1]
```diff
@@ -1,57 +1,57 @@
 var template = require('./templates');
```
Comment (vetom) [inline cards.js]: This can be deleted
